// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Stub.Template.StubSource
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\StubSource\FunctionReturnValueCodeTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class FunctionReturnValueCodeTemplate : FunctionBufferTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 7 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\StubSource\FunctionReturnValueCodeTemplate.tt"

	if (Target.HasReturn()) {

            
            #line default
            #line hidden
            this.Write("\t//Return latched value.\r\n\treturn latchReturn;\r\n");
            
            #line 12 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\StubSource\FunctionReturnValueCodeTemplate.tt"

	}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
