// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.GoogleTest.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class GoogleTestSourceTestCasePartTemplate : GoogleTestCodeTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nTEST_F(");
            
            #line 9 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTestClassName(this.TargetFunction)));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 9 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTestCaseName(TestCase, TargetFunction)));
            
            #line default
            #line hidden
            this.Write(")\r\n{\r\n");
            
            #line 11 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
	if (null != TargetFunction.Arguments) {	
            
            #line default
            #line hidden
            this.Write("\t//Declare argument for target\r\n");
            
            #line 13 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
		foreach (var argument in TargetFunction.Arguments) {	
            
            #line default
            #line hidden
            
            #line 14 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateCodeToDeclareArgumentPart(argument)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 15 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
		}	
            
            #line default
            #line hidden
            
            #line 16 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
	}	
            
            #line default
            #line hidden
            this.Write("\r\n\t//Setup test parameters.\r\n");
            
            #line 19 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
 foreach (var input in TestCase.Inputs) {	
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 20 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SetInputValuesPart(input)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 21 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
	}	
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 23 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateTargetFunctionCall(TargetFunction)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t//Check the test result by comparing the output with the expected value.\r\n");
            
            #line 26 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
 foreach (var expect in TestCase.Expects) {	
            
            #line default
            #line hidden
            this.Write("\tASSERT_EQ(");
            
            #line 27 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(expect.Value));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 27 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(expect.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 28 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestCasePartTemplate.tt"
	}	
            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
