// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.GoogleTest.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestDriverTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class GoogleTestSourceTestDriverTemplate : GoogleTestCodeTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/*\r\n\t");
            
            #line 9 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestDriverTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TargetFunction.Name));
            
            #line default
            #line hidden
            this.Write(" test driver.\r\n */\r\n");
            
            #line 11 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestDriverTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateIncludeHeaderCode(TargetFunction)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 12 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestDriverTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateDecalreGlobalVariableCode(TargetFunction)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n// Test target function\r\n");
            
            #line 15 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestDriverTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TargetFunction.ToString()));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 17 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestDriverTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateSetUpCode(TargetFunction)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 18 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceTestDriverTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateTestCaseCode(TargetFunction, Test)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
