// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.GoogleTest.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestHeaderTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class GoogleTestHeaderTemplate : GoogleTestCodeTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/*\r\n *\t");
            
            #line 9 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestHeaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TargetFunction.Name));
            
            #line default
            #line hidden
            this.Write(" header test driver header code.\r\n */\r\n#pragma once\r\n\r\nclass ");
            
            #line 13 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestHeaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTestClassName(TargetFunction)));
            
            #line default
            #line hidden
            this.Write(" : public ::testing::Test\r\n{\r\nprotected:\r\n\tvirtual void SetUp();\r\n\r\nprotected:\r\n}" +
                    ";\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
