// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.GoogleTest.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceSetUpMethodPartTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class GoogleTestSourceSetUpMethodPartTemplate : GoogleTestCodeTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("// Initialzie test dobule by calling initializing methods.\r\nvoid ");
            
            #line 9 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceSetUpMethodPartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTestClassName(TargetFunction)));
            
            #line default
            #line hidden
            this.Write("::SetUp()\r\n{\r\n");
            
            #line 11 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceSetUpMethodPartTemplate.tt"
 
	if (null != TargetFunction.SubFunctions) {
		foreach (var subFunction in TargetFunction.SubFunctions) {	

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 15 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceSetUpMethodPartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateTestDoubleInitializeMethodName(subFunction)));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 16 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceSetUpMethodPartTemplate.tt"

		}
	}

            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
