// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.GoogleTest.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceIncludePartTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class GoogleTestSourceIncludePartTemplate : GoogleTestCodeTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 8 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceIncludePartTemplate.tt"

	foreach (var stdHeader in StandardHeaders)
	{
		if ((!string.IsNullOrEmpty(stdHeader)) && (!string.IsNullOrWhiteSpace(stdHeader)))
		{

            
            #line default
            #line hidden
            this.Write("#include <");
            
            #line 14 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceIncludePartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(stdHeader));
            
            #line default
            #line hidden
            this.Write(">\r\n");
            
            #line 15 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceIncludePartTemplate.tt"

		}
	}

            
            #line default
            #line hidden
            this.Write("#include \"gtest/gtest.h\"\r\n");
            
            #line 20 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceIncludePartTemplate.tt"

	foreach (var userHeader in UserHeaders)
	{
		if ((!string.IsNullOrEmpty(userHeader)) && (!string.IsNullOrWhiteSpace(userHeader)))
		{

            
            #line default
            #line hidden
            this.Write("#include \"");
            
            #line 26 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceIncludePartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(userHeader));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 27 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceIncludePartTemplate.tt"

		}
	}

            
            #line default
            #line hidden
            
            #line 31 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceIncludePartTemplate.tt"

	if ((!string.IsNullOrEmpty(DriverHeaderFileName)) && (!string.IsNullOrWhiteSpace(DriverHeaderFileName)))
	{

            
            #line default
            #line hidden
            this.Write("#incluide \"");
            
            #line 35 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceIncludePartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DriverHeaderFileName));
            
            #line default
            #line hidden
            this.Write("\"\r\n");
            
            #line 36 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceIncludePartTemplate.tt"

	}

            
            #line default
            #line hidden
            
            #line 39 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceIncludePartTemplate.tt"

	if ((!string.IsNullOrEmpty(StubHeaderFileName)) && (!string.IsNullOrWhiteSpace(StubHeaderFileName)))
	{

            
            #line default
            #line hidden
            this.Write("#incluide \"");
            
            #line 43 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceIncludePartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StubHeaderFileName));
            
            #line default
            #line hidden
            this.Write("\"\r\n");
            
            #line 44 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\GTestDriverCodeGenerator\GoogleTest\Template\GoogleTestSourceIncludePartTemplate.tt"

	}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
