// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Stub.Template.Stub.Source
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using SourceTemplate = CodeGenerator.Stub.Template;
    using SourceTemplatePart = CodeGenerator.Stub.Template.Stub.Source.Part;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\Stub\Source\StubSourceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class StubSourceTemplate : StubTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 9 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\Stub\Source\StubSourceTemplate.tt"

	//ヘッダインクルード部分
	var includeTemplate = new IncludeHeaderTemplate(Config);
	includeTemplate.StubHeaderFileName = StubHeaderFileName;
	Write(includeTemplate.TransformText());

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 16 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\Stub\Source\StubSourceTemplate.tt"

	foreach (var targetFunctionItem in ParentFunction.SubFunctions)
	{
		//Declare buffers
		var buffDecTemplate = new SourceTemplatePart.BufferDeclareTemplate();
		buffDecTemplate.Target = targetFunctionItem;
		Write(buffDecTemplate.TransformText());

		WriteLine("");

		//Implement buffer initialize method.
		var buffInitMethodTemplate = new SourceTemplatePart.BufferInitMethodTemplate();
		buffInitMethodTemplate.Target = targetFunctionItem;
		Write(buffInitMethodTemplate.TransformText());

		WriteLine("");

		//Implement stub body.
		var stubMethodTemplate = new SourceTemplatePart.StubMethodTemplate();
		stubMethodTemplate.Target = targetFunctionItem;
		Write(stubMethodTemplate.TransformText());

		WriteLine("");

	}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
