// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Stub.Template.Stub.Source
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using SourceTemplate = CodeGenerator.Stub.Template;
    using SourceTemplatePart = CodeGenerator.Stub.Template.Stub.Source.Part;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\Stub\Source\StubHeaderTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class StubHeaderTemplate : StubTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 9 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\Stub\Source\StubHeaderTemplate.tt"

	//マクロ宣下部分
	var bufferSizeMacroTemplate = new FunctionBufferSizeMacroTemplate(Config);
	Write(bufferSizeMacroTemplate.TransformText());

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 15 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\Stub\Source\StubHeaderTemplate.tt"

	foreach (var targetFunctionItem in ParentFunction.SubFunctions)
	{
		//Declare argument buffers
		var bufferDecTemplate = new SourceTemplatePart.BufferDeclareExternTemplate();
		bufferDecTemplate.Target = targetFunctionItem;
		Write(bufferDecTemplate.TransformText());

		WriteLine("");

		//Declare initialize argument.
		var bufferInitMethodTemplate = new SourceTemplatePart.BufferInitMethodTemplate();
		bufferInitMethodTemplate.Target = targetFunctionItem;
		Write(bufferInitMethodTemplate.TransformText());

		WriteLine("");
	}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
