//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReader.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   テスト一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_SHEETN_NAME_TARGET_TEST_LIST {
            get {
                return ResourceManager.GetString("IDS_SHEETN_NAME_TARGET_TEST_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ○対象関数情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TABLE_NAME_TARGET_FUNCTION {
            get {
                return ResourceManager.GetString("IDS_TABLE_NAME_TARGET_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ○テスト対象関数一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TABLE_NAME_TARGET_TEST_FUNCTION_LIST {
            get {
                return ResourceManager.GetString("IDS_TABLE_NAME_TARGET_TEST_FUNCTION_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ○テスト/デシジョンテーブル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TABLE_NAME_TEST_CASE_DEFINITION {
            get {
                return ResourceManager.GetString("IDS_TABLE_NAME_TEST_CASE_DEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グローバル変数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_CATEGORY_COL_ITEM_GLOBAL_VAR {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_CATEGORY_COL_ITEM_GLOBAL_VAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   子関数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_CATEGORY_COL_ITEM_SUB_FUNCTION {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_CATEGORY_COL_ITEM_SUB_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト対象関数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_CATEGORY_COL_ITEM_TARGET_FUNCTION {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_CATEGORY_COL_ITEM_TARGET_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_CLASSIFICATION_COL_ITEM_ARGUMENT {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_CLASSIFICATION_COL_ITEM_ARGUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本体 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_CLASSIFICATION_COL_ITEM_BODY {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_CLASSIFICATION_COL_ITEM_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_CLASSIFICATION_COL_ITEM_EXTERNAL {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_CLASSIFICATION_COL_ITEM_EXTERNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内部 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_CLASSIFICATION_COL_ITEM_INTERNAL {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_CLASSIFICATION_COL_ITEM_INTERNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   種類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_COL_NAME_CATEGORY {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_COL_NAME_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内容 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_COL_NAME_CLASSIFICATION {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_COL_NAME_CLASSIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ型後置修飾 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_COL_NAME_DATA_POSTFIX {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_COL_NAME_DATA_POSTFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ型前置修飾 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_COL_NAME_DATA_PREFIX {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_COL_NAME_DATA_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ型 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_COL_NAME_DATA_TYPE {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_COL_NAME_DATA_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_COL_NAME_DIRECTION {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_COL_NAME_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_COL_NAME_FUNC_PARAM_NAME {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_COL_NAME_FUNC_PARAM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考/説明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_COL_NAME_REMARKS {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_COL_NAME_REMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   in/out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_DIRECTION_COL_ITEM_BOTH {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_DIRECTION_COL_ITEM_BOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_DIRECTION_COL_ITEM_INPUT {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_DIRECTION_COL_ITEM_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_FUNCTION_TABLE_DIRECTION_COL_ITEM_OUTPUT {
            get {
                return ResourceManager.GetString("IDS_TARGET_FUNCTION_TABLE_DIRECTION_COL_ITEM_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_TEST_FUNCTION_LIST_TABLE_COL_NAME_NO {
            get {
                return ResourceManager.GetString("IDS_TARGET_TEST_FUNCTION_LIST_TABLE_COL_NAME_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト定義シート名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_TEST_FUNCTION_LIST_TABLE_COL_NAME_TEST_DEF_SHEET_NAME {
            get {
                return ResourceManager.GetString("IDS_TARGET_TEST_FUNCTION_LIST_TABLE_COL_NAME_TEST_DEF_SHEET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソースファイル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_TEST_FUNCTION_LIST_TABLE_COL_NAME_TEST_FILE_NAME {
            get {
                return ResourceManager.GetString("IDS_TARGET_TEST_FUNCTION_LIST_TABLE_COL_NAME_TEST_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソースファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_TEST_FUNCTION_LIST_TABLE_COL_NAME_TEST_FILE_PATH {
            get {
                return ResourceManager.GetString("IDS_TARGET_TEST_FUNCTION_LIST_TABLE_COL_NAME_TEST_FILE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TARGET_TEST_FUNCTION_LIST_TABLE_COL_NAME_TEST_NAME {
            get {
                return ResourceManager.GetString("IDS_TARGET_TEST_FUNCTION_LIST_TABLE_COL_NAME_TEST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力/期待値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TEST_CASE_TABLE_COL_NAME_INPUT_CATEGORY {
            get {
                return ResourceManager.GetString("IDS_TEST_CASE_TABLE_COL_NAME_INPUT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TEST_CASE_TABLE_COL_NAME_PARAM_TYPE {
            get {
                return ResourceManager.GetString("IDS_TEST_CASE_TABLE_COL_NAME_PARAM_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   範囲 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TEST_CASE_TABLE_COL_NAME_RANGE {
            get {
                return ResourceManager.GetString("IDS_TEST_CASE_TABLE_COL_NAME_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   代表値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TEST_CASE_TABLE_COL_NAME_TYPICAL_VALUE {
            get {
                return ResourceManager.GetString("IDS_TEST_CASE_TABLE_COL_NAME_TYPICAL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変数名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TEST_CASE_TABLE_COL_NAME_VARIABLE_NAME {
            get {
                return ResourceManager.GetString("IDS_TEST_CASE_TABLE_COL_NAME_VARIABLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   期待値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TEST_CASE_TABLE_INPUT_CATEGORY_COL_ITEM_EXPECT {
            get {
                return ResourceManager.GetString("IDS_TEST_CASE_TABLE_INPUT_CATEGORY_COL_ITEM_EXPECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TEST_CASE_TABLE_INPUT_CATEGORY_COL_ITEM_INPUT {
            get {
                return ResourceManager.GetString("IDS_TEST_CASE_TABLE_INPUT_CATEGORY_COL_ITEM_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_TEST_CASE_TABLE_PARAM_TYPE_COL_ARGUMENT {
            get {
                return ResourceManager.GetString("IDS_TEST_CASE_TABLE_PARAM_TYPE_COL_ARGUMENT", resourceCulture);
            }
        }
    }
}
