// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.TestDriver.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\src\GoogleTestDriverCodeGenerator\Template\GoogleTestIncludeTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class GoogleTestIncludeTemplate : GoogleTestTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 7 "E:\development\AutoTestPrep\dev\src\GoogleTestDriverCodeGenerator\Template\GoogleTestIncludeTemplate.tt"

	foreach (var headerFile in Config.StandardHeaderFiles) {
		if ((!string.IsNullOrEmpty(headerFile)) && (!string.IsNullOrWhiteSpace(headerFile))) {

            
            #line default
            #line hidden
            this.Write("#include <");
            
            #line 11 "E:\development\AutoTestPrep\dev\src\GoogleTestDriverCodeGenerator\Template\GoogleTestIncludeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(headerFile));
            
            #line default
            #line hidden
            this.Write(">\r\n");
            
            #line 12 "E:\development\AutoTestPrep\dev\src\GoogleTestDriverCodeGenerator\Template\GoogleTestIncludeTemplate.tt"

		}
	}

            
            #line default
            #line hidden
            this.Write("#include \"gtest/gtest.h\"\r\n");
            
            #line 17 "E:\development\AutoTestPrep\dev\src\GoogleTestDriverCodeGenerator\Template\GoogleTestIncludeTemplate.tt"

	foreach (var headerFile in Config.UserHeaderFiles) { 
		if ((!string.IsNullOrEmpty(headerFile)) && (!string.IsNullOrWhiteSpace(headerFile))) {

            
            #line default
            #line hidden
            this.Write("#include \"");
            
            #line 21 "E:\development\AutoTestPrep\dev\src\GoogleTestDriverCodeGenerator\Template\GoogleTestIncludeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(headerFile));
            
            #line default
            #line hidden
            this.Write("\"\r\n");
            
            #line 22 "E:\development\AutoTestPrep\dev\src\GoogleTestDriverCodeGenerator\Template\GoogleTestIncludeTemplate.tt"

		}
	}

            
            #line default
            #line hidden
            
            #line 26 "E:\development\AutoTestPrep\dev\src\GoogleTestDriverCodeGenerator\Template\GoogleTestIncludeTemplate.tt"

	if ((!string.IsNullOrEmpty(DriverHeaderFileName)) && (!string.IsNullOrWhiteSpace(DriverHeaderFileName))) {

            
            #line default
            #line hidden
            this.Write("#include \"");
            
            #line 29 "E:\development\AutoTestPrep\dev\src\GoogleTestDriverCodeGenerator\Template\GoogleTestIncludeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DriverHeaderFileName));
            
            #line default
            #line hidden
            this.Write("\"\r\n");
            
            #line 30 "E:\development\AutoTestPrep\dev\src\GoogleTestDriverCodeGenerator\Template\GoogleTestIncludeTemplate.tt"

	}

            
            #line default
            #line hidden
            
            #line 33 "E:\development\AutoTestPrep\dev\src\GoogleTestDriverCodeGenerator\Template\GoogleTestIncludeTemplate.tt"

	if ((!string.IsNullOrEmpty(StubHeaderFileName)) && (!string.IsNullOrWhiteSpace(StubHeaderFileName))) {

            
            #line default
            #line hidden
            this.Write("#include \"");
            
            #line 36 "E:\development\AutoTestPrep\dev\src\GoogleTestDriverCodeGenerator\Template\GoogleTestIncludeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StubHeaderFileName));
            
            #line default
            #line hidden
            this.Write("\"\r\n");
            
            #line 37 "E:\development\AutoTestPrep\dev\src\GoogleTestDriverCodeGenerator\Template\GoogleTestIncludeTemplate.tt"

	}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
