// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestDoubleCodeGenerator.TestDouble.Template.Body
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using TestReader.Model;
    using TestDoubleCodeGenerator.Rule;
    using Logger;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\Body\FunctionWithReturnValueBufferTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class FunctionWithReturnValueBufferTemplate : BufferTemplateCommonBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 11 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\Body\FunctionWithReturnValueBufferTemplate.tt"
	
	string	calledCntBuffName = NameRule.CalledCount((Function)Target);
	string	returnValueBufferName = NameRule.ReturnValue((Function)Target);
	string	returnBufferName = "_ret_val";
	string	returnDataType = Target.ActualDataType();

	Log.DEBUG($"{nameof(calledCntBuffName), 16} = {calledCntBuffName}");
	Log.DEBUG($"{nameof(returnValueBufferName), 16} = {returnValueBufferName}");
	Log.DEBUG($"{nameof(returnBufferName), 16} = {returnBufferName}");
	Log.DEBUG($"{nameof(returnDataType), 16} = {returnDataType}");

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 22 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\Body\FunctionWithReturnValueBufferTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(returnDataType));
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 22 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\Body\FunctionWithReturnValueBufferTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(returnBufferName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 22 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\Body\FunctionWithReturnValueBufferTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(returnValueBufferName));
            
            #line default
            #line hidden
            this.Write("[");
            
            #line 22 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\Body\FunctionWithReturnValueBufferTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(calledCntBuffName));
            
            #line default
            #line hidden
            this.Write("];\r\n\r\n\t");
            
            #line 24 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\Body\FunctionWithReturnValueBufferTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(calledCntBuffName));
            
            #line default
            #line hidden
            this.Write("++;\r\n\r\n\treturn ");
            
            #line 26 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\Body\FunctionWithReturnValueBufferTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(returnBufferName));
            
            #line default
            #line hidden
            this.Write(";");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
