// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Stub.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\IncludeHeaderTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class IncludeHeaderTemplate : ABufferTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 7 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\IncludeHeaderTemplate.tt"

	string _standardHeaderInclude = "No standard header files specified to include.\r\n";
	try {
		bool isTop = true;
		foreach (var item in Config.StandardHeaderFiles) {
			if (true == isTop) {
				_standardHeaderInclude = string.Empty;
				isTop = false;
			}
			_standardHeaderInclude += $"#include <{item}>";
			_standardHeaderInclude += "\r\n";
		}
	}
	catch (NullReferenceException) {
		_standardHeaderInclude = "No standard header files specified to include.\r\n";
	}
	finally {
		Write(_standardHeaderInclude);
	}

            
            #line default
            #line hidden
            
            #line 27 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\IncludeHeaderTemplate.tt"

	string _userHeaderInclude = "No user header files specified to include.\r\n";
	try {
		bool isTop = true;
		foreach (var item in Config.UserHeaderFiles) {
			if (true == isTop) {
				_userHeaderInclude = string.Empty;
				isTop = false;
			}
			_userHeaderInclude += $"#include \"{item}\"";
			_userHeaderInclude += "\r\n";
		}
	}
	catch (NullReferenceException) {
		_userHeaderInclude = "No user header files specified to include.\r\n";
	}
	finally {
		Write(_userHeaderInclude);
	}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
