//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTestPrep.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoTestPrep.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AutoTestPrep に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_APP_TITLE {
            get {
                return ResourceManager.GetString("IDS_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インクルードディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_HEADER_INFORMATION_HEADER_INCLUDE_DIRS_OF_DRIVER {
            get {
                return ResourceManager.GetString("IDS_HEADER_INFORMATION_HEADER_INCLUDE_DIRS_OF_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インクルードディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_HEADER_INFORMATION_HEADER_INCLUDE_DIRS_OF_STUB {
            get {
                return ResourceManager.GetString("IDS_HEADER_INFORMATION_HEADER_INCLUDE_DIRS_OF_STUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘッダ情報(ドライバ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_HEADER_INFORMATION_OF_DRIVER {
            get {
                return ResourceManager.GetString("IDS_HEADER_INFORMATION_OF_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘッダ情報(スタブ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_HEADER_INFORMATION_OF_STUB {
            get {
                return ResourceManager.GetString("IDS_HEADER_INFORMATION_OF_STUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準ヘッダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_HEADER_INFORMATION_STANDARD_HEADERS_OF_DRIVER {
            get {
                return ResourceManager.GetString("IDS_HEADER_INFORMATION_STANDARD_HEADERS_OF_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準ヘッダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_HEADER_INFORMATION_STANDARD_HEADERS_OF_STUB {
            get {
                return ResourceManager.GetString("IDS_HEADER_INFORMATION_STANDARD_HEADERS_OF_STUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザヘッダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_HEADER_INFORMATION_USER_HEADERS_OF_DRIVER {
            get {
                return ResourceManager.GetString("IDS_HEADER_INFORMATION_USER_HEADERS_OF_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザヘッダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_HEADER_INFORMATION_USER_HEADERS_OF_STUB {
            get {
                return ResourceManager.GetString("IDS_HEADER_INFORMATION_USER_HEADERS_OF_STUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライブラリディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_LIBRARY_DIRS {
            get {
                return ResourceManager.GetString("IDS_LIBRARY_DIRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライブラリファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_LIBRARY_FILES {
            get {
                return ResourceManager.GetString("IDS_LIBRARY_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライブラリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_LIBRARY_INFORMATION {
            get {
                return ResourceManager.GetString("IDS_LIBRARY_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マクロ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MACRO {
            get {
                return ResourceManager.GetString("IDS_MACRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マクロ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MACRO_ITEM {
            get {
                return ResourceManager.GetString("IDS_MACRO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MENU_ITEM_EXECUTE {
            get {
                return ResourceManager.GetString("IDS_MENU_ITEM_EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト仕様書 読み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MENU_ITEM_EXECUTE_READ_TEST_SPEC {
            get {
                return ResourceManager.GetString("IDS_MENU_ITEM_EXECUTE_READ_TEST_SPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタブ・ドライバ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MENU_ITEM_EXECUTE_TEST_DOUBLE {
            get {
                return ResourceManager.GetString("IDS_MENU_ITEM_EXECUTE_TEST_DOUBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラグイン管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MENU_ITEM_EXECUTE_TEST_PLUGIN_MANAGER {
            get {
                return ResourceManager.GetString("IDS_MENU_ITEM_EXECUTE_TEST_PLUGIN_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラグイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MENU_ITEM_EXECUTE_TEST_PLUGINS {
            get {
                return ResourceManager.GetString("IDS_MENU_ITEM_EXECUTE_TEST_PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MENU_ITEM_FILE {
            get {
                return ResourceManager.GetString("IDS_MENU_ITEM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MENU_ITEM_FILE_EXIT {
            get {
                return ResourceManager.GetString("IDS_MENU_ITEM_FILE_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MENU_ITEM_FILE_NEW {
            get {
                return ResourceManager.GetString("IDS_MENU_ITEM_FILE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MENU_ITEM_FILE_OPEN {
            get {
                return ResourceManager.GetString("IDS_MENU_ITEM_FILE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MENU_ITEM_FILE_SAVE {
            get {
                return ResourceManager.GetString("IDS_MENU_ITEM_FILE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前を付けて保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MENU_ITEM_FILE_SAVE_AS {
            get {
                return ResourceManager.GetString("IDS_MENU_ITEM_FILE_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MENU_ITEM_HELP {
            get {
                return ResourceManager.GetString("IDS_MENU_ITEM_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_MENU_ITEM_HELP_VERSION {
            get {
                return ResourceManager.GetString("IDS_MENU_ITEM_HELP_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタブ情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_TEST_DOUBLE_BUFFER_INFORMATION {
            get {
                return ResourceManager.GetString("IDS_TEST_DOUBLE_BUFFER_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタブバッファサイズ1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_TEST_DOUBLE_BUFFER_SIZE_1 {
            get {
                return ResourceManager.GetString("IDS_TEST_DOUBLE_BUFFER_SIZE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタブバッファサイズ2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_TEST_DOUBLE_BUFFER_SIZE_2 {
            get {
                return ResourceManager.GetString("IDS_TEST_DOUBLE_BUFFER_SIZE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_TEST_INFO_CATEGORY_NAME {
            get {
                return ResourceManager.GetString("IDS_TEST_INFO_CATEGORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力ソースルートフォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_TEST_INFO_INPUT_ROOT_DIR_PATH {
            get {
                return ResourceManager.GetString("IDS_TEST_INFO_INPUT_ROOT_DIR_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力先フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_TEST_INFO_OUTPUT_DIR_PATH {
            get {
                return ResourceManager.GetString("IDS_TEST_INFO_OUTPUT_DIR_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力(テスト定義ファイル) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IDS_TEST_SPEC_FILE_PATH {
            get {
                return ResourceManager.GetString("IDS_TEST_SPEC_FILE_PATH", resourceCulture);
            }
        }
    }
}
