// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Stub.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\FunctionBufferSizeMacroTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class FunctionBufferSizeMacroTemplate : ABufferTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("#ifndef\tSTUB_BUFFER_SIZE_1\r\n#define\tSTUB_BUFFER_SIZE_1\t\t\t(");
            
            #line 8 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\FunctionBufferSizeMacroTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.BufferSize1));
            
            #line default
            #line hidden
            this.Write(")\r\n#endif\r\n#ifndef\tSTUB_BUFFER_SIZE_2\r\n#define\tSTUB_BUFFER_SIZE_2\t\t\t(");
            
            #line 11 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\FunctionBufferSizeMacroTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Config.BufferSize2));
            
            #line default
            #line hidden
            this.Write(")\r\n#endif\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
