// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestDoubleCodeGenerator.TestDouble.Template.Buffer
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using TestDoubleCodeGenerator.Rule;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\Buffer\PointerArgumentBufferTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class PointerArgumentBufferTemplate : ArgumentBufferTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 9 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\Buffer\PointerArgumentBufferTemplate.tt"

	string	dataType = Argument.DataType;
	string	buffName = NameRule.SinglePointerArgumentValueBuffer(Function, Argument);
	string	buffDeclare = NameRule.DeclareFormat(dataType, buffName);
	string	sizeBuffName = NameRule.SinglePointerArgumentValueSizeBuffer(Function, Argument);
	string	sizeBuffDeclare = NameRule.DeclareFormat("long", sizeBuffName);
	string	buffSize1Macro = NameRule.BufferSize1MacroName;
	string	buffSize2Macro = NameRule.BufferSize2MacroName;

            
            #line default
            #line hidden
            
            #line 18 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\Buffer\PointerArgumentBufferTemplate.tt"
 base.TransformText(); 
            
            #line default
            #line hidden
            
            #line 19 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\Buffer\PointerArgumentBufferTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BufferDeclareCode()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 20 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\Buffer\PointerArgumentBufferTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BuffSizeDeclare()));
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
