// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestDoubleCodeGenerator.TestDouble.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\TestDoubleSourceDeclareBufferPartTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class TestDoubleSourceDeclareBufferPartTemplate : TestDoubleSourceImplementCommonBasePartTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("// Test double buffers.\r\n");
            
            #line 9 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\TestDoubleSourceDeclareBufferPartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CalledCountDeclare()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 10 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\TestDoubleSourceDeclareBufferPartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TestDoubleReturnValueDeclare()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n// Argument buffers.\r\n");
            
            #line 13 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\TestDoubleSourceDeclareBufferPartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ArgumentBufferDeclare()));
            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
