// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestDoubleCodeGenerator.TestDouble.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Logger;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\TestDoubleSourceIncludePartTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class TestDoubleSourceIncludePartTemplate : TestDoubleCodeTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 9 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\TestDoubleSourceIncludePartTemplate.tt"
 Log.TRACE(); 
            
            #line default
            #line hidden
            
            #line 10 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\TestDoubleSourceIncludePartTemplate.tt"

	foreach (var stdHeader in StandardHeaders)
	{
		if ((!string.IsNullOrEmpty(stdHeader)) && (!string.IsNullOrWhiteSpace(stdHeader)))
		{
			Log.DEBUG($"{nameof(stdHeader), 16} = {stdHeader}");

            
            #line default
            #line hidden
            this.Write("#include <");
            
            #line 17 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\TestDoubleSourceIncludePartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(stdHeader));
            
            #line default
            #line hidden
            this.Write(">\r\n");
            
            #line 18 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\TestDoubleSourceIncludePartTemplate.tt"

		}
	}

            
            #line default
            #line hidden
            
            #line 22 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\TestDoubleSourceIncludePartTemplate.tt"

	foreach (var userHeader in UserHeaders)
	{
		if ((!string.IsNullOrEmpty(userHeader)) && (!string.IsNullOrWhiteSpace(userHeader)))
		{
			Log.DEBUG($"{nameof(userHeader), 16} = {userHeader}");

            
            #line default
            #line hidden
            this.Write("#include \"");
            
            #line 29 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\TestDoubleSourceIncludePartTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(userHeader));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 30 "E:\development\AutoTestPrep\dev\.NET\src\CodeGenerator\TestDoubleCodeGenerator\TestDouble\Template\TestDoubleSourceIncludePartTemplate.tt"

		}
	}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
