// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Stub.Template.Stub.Source.Part
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\Stub\Source\Part\StubMethodTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class StubMethodTemplate : TemplateCommonBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/*\r\n *\tStub method of ");
            
            #line 8 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\Stub\Source\Part\StubMethodTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Target.Name));
            
            #line default
            #line hidden
            this.Write("\r\n */\r\n");
            
            #line 10 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\Stub\Source\Part\StubMethodTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Target.ToString()));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 12 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\Stub\Source\Part\StubMethodTemplate.tt"

	//戻り値をラッチする処理
	var funcReturnLatchTemplate = FuncReturnLatchFactory.Create(Target, null);
	Write(funcReturnLatchTemplate.TransformText());

            
            #line default
            #line hidden
            
            #line 17 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\Stub\Source\Part\StubMethodTemplate.tt"

	//引数の処理
	foreach (var item in Target.Arguments) 
	{
		var argTemplate = ArgumentFactory.Create(Target, item);
		Write(argTemplate.TransformText());
	}

            
            #line default
            #line hidden
            
            #line 25 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\Stub\Source\Part\StubMethodTemplate.tt"

	//呼び出し回数更新
	var calledCountTemplate = CalledCountFactory.Create(Target, null);
	Write(calledCountTemplate.TransformText());

            
            #line default
            #line hidden
            
            #line 30 "E:\development\AutoTestPrep\dev\src\StubCodeGenerator\Template\Stub\Source\Part\StubMethodTemplate.tt"

	//戻り値の処理
	var retCodeTemplate = ReturnCodeFactory.Create(Target, null);
	Write(retCodeTemplate.TransformText());

            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
